"""
Property Lead Marketing Routes
Handles brochure generation, landing page creation, email sending, and property data scraping
"""
from fastapi import APIRouter, Depends, HTTPException, BackgroundTasks
from fastapi.responses import StreamingResponse
from typing import Optional, List
from datetime import datetime, timezone
from pydantic import BaseModel
import uuid
import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.application import MIMEApplication

from database import db
from utils.auth import get_current_user
from models.user import UserRole
from services.brochure_generator import generate_brochure, calculate_lead_score
from services.foldable_brochure import generate_foldable_brochure, generate_foldable_brochure_page1
from services.property_scraper import scrape_property_data


def get_site_url() -> str:
    site_url = os.environ.get("SITE_URL")
    if not site_url:
        raise HTTPException(status_code=500, detail="SITE_URL is not configured")
    return site_url.rstrip("/")


def build_landing_page_url(slug: str) -> str:
    return f"{get_site_url()}/landing/{slug}"

router = APIRouter()


class BrochureRequest(BaseModel):
    template: str = 'flyer'  # flyer, postcard, trifold, foldable
    include_qr: bool = True
    property_images: Optional[List[str]] = None


class EmailBrochureRequest(BaseModel):
    template: str = 'flyer'
    recipient_email: str
    subject: Optional[str] = None
    message: Optional[str] = None
    include_landing_page_link: bool = True


class CreateListingFromLeadRequest(BaseModel):
    create_landing_page: bool = True
    theme: str = 'luxury'
    custom_headline: Optional[str] = None
    custom_description: Optional[str] = None


# ============ LEAD SCORING ============

@router.get("/{lead_id}/score")
async def get_lead_score(lead_id: str, current_user: dict = Depends(get_current_user)):
    """Get the lead score and breakdown"""
    lead = await db.property_leads.find_one({"id": lead_id}, {"_id": 0})
    if not lead:
        raise HTTPException(status_code=404, detail="Property lead not found")
    
    score_data = calculate_lead_score(lead)
    return score_data


# ============ BROCHURE GENERATION ============

@router.post("/{lead_id}/brochure/generate")
async def generate_brochure_endpoint(
    lead_id: str,
    request: BrochureRequest,
    current_user: dict = Depends(get_current_user)
):
    """Generate a brochure PDF for download"""
    if current_user["role"] not in [UserRole.SUPERUSER, UserRole.ADMIN]:
        raise HTTPException(status_code=403, detail="Admin access required")
    
    # Get lead data
    lead = await db.property_leads.find_one({"id": lead_id}, {"_id": 0})
    if not lead:
        raise HTTPException(status_code=404, detail="Property lead not found")
    
    # Get agent info from settings or current user
    settings = await db.settings.find_one({"type": "agent"}, {"_id": 0})
    agent_info = {
        "name": settings.get("agent_name", current_user.get("name", "Agent")) if settings else current_user.get("name", "Agent"),
        "phone": settings.get("agent_phone", "") if settings else "",
        "email": settings.get("agent_email", current_user.get("email", "")) if settings else current_user.get("email", ""),
        "title": settings.get("agent_title", "Real Estate Specialist") if settings else "Real Estate Specialist"
    }
    
    # Get branding
    branding = await db.settings.find_one({"type": "branding"}, {"_id": 0})
    
    # Check for landing page URL
    landing_page_url = None
    if request.include_qr and lead.get("landing_page_id"):
        landing_page = await db.landing_pages.find_one({"id": lead["landing_page_id"]}, {"_id": 0})
        if landing_page:
            landing_page_url = build_landing_page_url(landing_page["slug"])
    
    # Generate brochure based on template type
    if request.template == 'foldable':
        # Generate 2-page foldable brochure
        pdf_buffer = await generate_foldable_brochure(
            lead=lead,
            agent_info=agent_info,
            branding=branding,
            landing_page_url=landing_page_url,
            property_images=request.property_images or lead.get('images', [])
        )
        address_slug = lead.get('address', 'property').lower().replace(' ', '-')[:30]
        filename = f"brochure-{address_slug}-foldable.pdf"
    else:
        # Generate standard brochure
        pdf_buffer, filename = await generate_brochure(
            lead=lead,
            agent_info=agent_info,
            template=request.template,
            landing_page_url=landing_page_url
        )
    
    # Log activity
    activity_entry = {
        "type": "brochure_generated",
        "description": f"Brochure ({request.template}) generated by {current_user['name']}",
        "user": current_user["name"],
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "data": {"template": request.template}
    }
    
    await db.property_leads.update_one(
        {"id": lead_id},
        {"$push": {"activity": activity_entry}}
    )
    
    return StreamingResponse(
        pdf_buffer,
        media_type="application/pdf",
        headers={"Content-Disposition": f"attachment; filename={filename}"}
    )


@router.post("/{lead_id}/brochure/preview")
async def preview_brochure(
    lead_id: str,
    request: BrochureRequest,
    current_user: dict = Depends(get_current_user)
):
    """Generate brochure for preview (inline display)"""
    lead = await db.property_leads.find_one({"id": lead_id}, {"_id": 0})
    if not lead:
        raise HTTPException(status_code=404, detail="Property lead not found")
    
    settings = await db.settings.find_one({"type": "agent"}, {"_id": 0})
    agent_info = {
        "name": settings.get("agent_name", current_user.get("name", "Agent")) if settings else current_user.get("name", "Agent"),
        "phone": settings.get("agent_phone", "") if settings else "",
        "email": settings.get("agent_email", current_user.get("email", "")) if settings else current_user.get("email", ""),
        "title": settings.get("agent_title", "Real Estate Specialist") if settings else "Real Estate Specialist"
    }
    
    # Get branding
    branding = await db.settings.find_one({"type": "branding"}, {"_id": 0})
    
    landing_page_url = None
    if request.include_qr and lead.get("landing_page_id"):
        landing_page = await db.landing_pages.find_one({"id": lead["landing_page_id"]}, {"_id": 0})
        if landing_page:
            landing_page_url = build_landing_page_url(landing_page["slug"])
    
    # Generate brochure based on template type
    if request.template == 'foldable':
        pdf_buffer = await generate_foldable_brochure(
            lead=lead,
            agent_info=agent_info,
            branding=branding,
            landing_page_url=landing_page_url,
            property_images=request.property_images or lead.get('images', [])
        )
        address_slug = lead.get('address', 'property').lower().replace(' ', '-')[:30]
        filename = f"brochure-{address_slug}-foldable.pdf"
    else:
        pdf_buffer, filename = await generate_brochure(
            lead=lead,
            agent_info=agent_info,
            template=request.template,
            landing_page_url=landing_page_url
        )
    
    return StreamingResponse(
        pdf_buffer,
        media_type="application/pdf",
        headers={"Content-Disposition": f"inline; filename={filename}"}
    )


# ============ EMAIL BROCHURE ============

@router.post("/{lead_id}/brochure/email")
async def email_brochure(
    lead_id: str,
    request: EmailBrochureRequest,
    background_tasks: BackgroundTasks,
    current_user: dict = Depends(get_current_user)
):
    """Email the brochure to the property owner"""
    if current_user["role"] not in [UserRole.SUPERUSER, UserRole.ADMIN]:
        raise HTTPException(status_code=403, detail="Admin access required")
    
    lead = await db.property_leads.find_one({"id": lead_id}, {"_id": 0})
    if not lead:
        raise HTTPException(status_code=404, detail="Property lead not found")
    
    # Get SMTP settings
    smtp_settings = await db.settings.find_one({"type": "smtp"}, {"_id": 0})
    if not smtp_settings or not smtp_settings.get("host"):
        raise HTTPException(status_code=400, detail="SMTP not configured. Please configure email settings first.")
    
    # Get agent info
    settings = await db.settings.find_one({"type": "agent"}, {"_id": 0})
    agent_info = {
        "name": settings.get("agent_name", current_user.get("name", "Agent")) if settings else current_user.get("name", "Agent"),
        "phone": settings.get("agent_phone", "") if settings else "",
        "email": settings.get("agent_email", current_user.get("email", "")) if settings else current_user.get("email", ""),
        "title": settings.get("agent_title", "Real Estate Specialist") if settings else "Real Estate Specialist"
    }
    
    # Get landing page URL if available
    landing_page_url = None
    if request.include_landing_page_link and lead.get("landing_page_id"):
        landing_page = await db.landing_pages.find_one({"id": lead["landing_page_id"]}, {"_id": 0})
        if landing_page:
            landing_page_url = build_landing_page_url(landing_page["slug"])
    
    # Generate brochure
    pdf_buffer, filename = await generate_brochure(
        lead=lead,
        agent_info=agent_info,
        template=request.template,
        landing_page_url=landing_page_url
    )
    
    # Prepare email
    owner_name = lead.get("owner_name", "Homeowner")
    address = lead.get("address", "your property")
    
    subject = request.subject or f"Exclusive Market Analysis for {address}"
    
    default_message = f"""
Dear {owner_name},

I hope this message finds you well. I wanted to reach out regarding your property at {address}.

After analyzing the current market conditions in {lead.get('city', 'your area')}, I believe there may be an excellent opportunity to discuss your property's potential.

I've prepared a personalized brochure with details about your property and current market insights. Please find it attached to this email.

{f'You can also view more information online at: {landing_page_url}' if landing_page_url else ''}

I would love to schedule a brief, no-obligation conversation to discuss how I can help you maximize the value of your property.

Please feel free to reach out at your convenience.

Best regards,
{agent_info['name']}
{agent_info['title']}
{agent_info['phone']}
{agent_info['email']}

Hidden Haven Realty
"""
    
    message_body = request.message or default_message
    
    # Send email in background
    async def send_email_task():
        try:
            msg = MIMEMultipart()
            msg['Subject'] = subject
            msg['From'] = smtp_settings.get('from_email', agent_info['email'])
            msg['To'] = request.recipient_email
            
            # Add HTML body
            html_body = f"""
            <html>
            <body style="font-family: Arial, sans-serif; line-height: 1.6; color: #0a1628;">
            {message_body.replace(chr(10), '<br/>')}
            </body>
            </html>
            """
            msg.attach(MIMEText(html_body, 'html'))
            
            # Attach PDF
            pdf_attachment = MIMEApplication(pdf_buffer.read(), _subtype='pdf')
            pdf_attachment.add_header('Content-Disposition', 'attachment', filename=filename)
            msg.attach(pdf_attachment)
            
            # Send via SMTP
            with smtplib.SMTP(smtp_settings['host'], smtp_settings.get('port', 587)) as server:
                if smtp_settings.get('use_tls', True):
                    server.starttls()
                if smtp_settings.get('username') and smtp_settings.get('password'):
                    server.login(smtp_settings['username'], smtp_settings['password'])
                server.send_message(msg)
            
            # Log success
            await db.property_leads.update_one(
                {"id": lead_id},
                {"$push": {"activity": {
                    "type": "brochure_emailed",
                    "description": f"Brochure emailed to {request.recipient_email} by {current_user['name']}",
                    "user": current_user["name"],
                    "timestamp": datetime.now(timezone.utc).isoformat(),
                    "data": {
                        "recipient": request.recipient_email,
                        "template": request.template,
                        "landing_page_url": landing_page_url
                    }
                }}}
            )
            
        except Exception as e:
            print(f"Email send error: {e}")
            # Log failure
            await db.property_leads.update_one(
                {"id": lead_id},
                {"$push": {"activity": {
                    "type": "email_failed",
                    "description": f"Failed to email brochure: {str(e)}",
                    "user": current_user["name"],
                    "timestamp": datetime.now(timezone.utc).isoformat()
                }}}
            )
    
    background_tasks.add_task(send_email_task)
    
    return {
        "message": f"Email queued for delivery to {request.recipient_email}",
        "recipient": request.recipient_email,
        "template": request.template,
        "landing_page_url": landing_page_url
    }


# ============ CREATE LISTING FROM LEAD ============

@router.post("/{lead_id}/create-listing")
async def create_listing_from_lead(
    lead_id: str,
    request: CreateListingFromLeadRequest,
    current_user: dict = Depends(get_current_user)
):
    """Create a property listing from a lead"""
    if current_user["role"] not in [UserRole.SUPERUSER, UserRole.ADMIN]:
        raise HTTPException(status_code=403, detail="Admin access required")
    
    lead = await db.property_leads.find_one({"id": lead_id}, {"_id": 0})
    if not lead:
        raise HTTPException(status_code=404, detail="Property lead not found")
    
    # Check if listing already exists
    if lead.get("listing_id"):
        existing = await db.properties.find_one({"id": lead["listing_id"]}, {"_id": 0})
        if existing:
            return {
                "message": "Listing already exists for this lead",
                "listing": existing,
                "listing_id": lead["listing_id"]
            }
    
    now = datetime.now(timezone.utc).isoformat()
    listing_id = str(uuid.uuid4())
    
    # Create listing from lead data
    listing = {
        "id": listing_id,
        "title": f"{lead.get('address', 'Property')}",
        "address": lead.get("address", ""),
        "city": lead.get("city", ""),
        "state": lead.get("state", "FL"),
        "zip_code": lead.get("zip_code", ""),
        "county": lead.get("county", ""),
        "price": lead.get("estimated_value", 0),
        "property_type": lead.get("property_type", "single_family"),
        "bedrooms": lead.get("bedrooms"),
        "bathrooms": lead.get("bathrooms"),
        "sqft": lead.get("sqft"),
        "square_feet": lead.get("sqft"),  # Legacy field
        "lot_size": lead.get("lot_size"),
        "year_built": lead.get("year_built"),
        "description": request.custom_description or f"Beautiful property located at {lead.get('address', '')} in {lead.get('city', '')}.",
        "features": [],
        "images": [],
        "status": "active",
        "mls_number": "",
        "source": "property_lead",
        "source_lead_id": lead_id,
        "created_at": now,
        "updated_at": now
    }
    
    await db.properties.insert_one(listing)
    
    # Update lead with listing reference
    await db.property_leads.update_one(
        {"id": lead_id},
        {
            "$set": {"listing_id": listing_id, "updated_at": now},
            "$push": {"activity": {
                "type": "listing_created",
                "description": f"Listing created from lead by {current_user['name']}",
                "user": current_user["name"],
                "timestamp": now,
                "data": {"listing_id": listing_id}
            }}
        }
    )
    
    result = {
        "message": "Listing created successfully",
        "listing_id": listing_id,
        "listing": listing
    }
    
    # Optionally create landing page
    if request.create_landing_page:
        import re
        
        # Generate slug
        full_address = f"{listing['address']} {listing['city']} {listing['state']}"
        slug = re.sub(r'[^a-z0-9\s-]', '', full_address.lower())
        slug = re.sub(r'[\s]+', '-', slug)
        slug = re.sub(r'-+', '-', slug).strip('-')
        
        # Ensure unique slug
        slug_exists = await db.landing_pages.find_one({"slug": slug})
        if slug_exists:
            slug = f"{slug}-{str(uuid.uuid4())[:8]}"
        
        # Get agent info
        settings = await db.settings.find_one({"type": "agent"}, {"_id": 0})
        
        landing_page_id = str(uuid.uuid4())
        
        landing_page = {
            "id": landing_page_id,
            "listing_id": listing_id,
            "slug": slug,
            "custom_headline": request.custom_headline or listing["title"],
            "custom_description": listing["description"],
            "videos": [],
            "additional_images": [],
            "virtual_tour_url": "",
            "show_map": True,
            "show_contact_form": True,
            "agent_name": settings.get("agent_name", "") if settings else "",
            "agent_phone": settings.get("agent_phone", "") if settings else "",
            "agent_email": settings.get("agent_email", "") if settings else "",
            "agent_photo": settings.get("agent_photo", "") if settings else "",
            "theme": request.theme,
            "status": "draft",
            "preview_url": build_landing_page_url(slug),
            "created_at": now,
            "updated_at": now
        }
        
        await db.landing_pages.insert_one(landing_page)
        
        # Update lead with landing page reference
        await db.property_leads.update_one(
            {"id": lead_id},
            {
                "$set": {
                    "landing_page_id": landing_page_id,
                    "landing_page_url": build_landing_page_url(landing_page["slug"])
                },
                "$push": {"activity": {
                    "type": "landing_page_created",
                    "description": f"Landing page created by {current_user['name']}",
                    "user": current_user["name"],
                    "timestamp": now,
                    "data": {
                        "landing_page_id": landing_page_id,
                        "slug": slug
                    }
                }}
            }
        )
        
        result["landing_page_id"] = landing_page_id
        result["landing_page_url"] = build_landing_page_url(landing_page["slug"])
        result["landing_page"] = landing_page
    
    return result


# ============ UPLOAD VIDEO TO LEAD ============

@router.post("/{lead_id}/upload-video")
async def upload_video_to_lead(
    lead_id: str,
    video_url: str,
    video_title: Optional[str] = None,
    current_user: dict = Depends(get_current_user)
):
    """Add a video URL to the property lead (for landing page)"""
    if current_user["role"] not in [UserRole.SUPERUSER, UserRole.ADMIN]:
        raise HTTPException(status_code=403, detail="Admin access required")
    
    lead = await db.property_leads.find_one({"id": lead_id}, {"_id": 0})
    if not lead:
        raise HTTPException(status_code=404, detail="Property lead not found")
    
    video_entry = {
        "id": str(uuid.uuid4()),
        "url": video_url,
        "title": video_title or "Property Walkthrough",
        "uploaded_at": datetime.now(timezone.utc).isoformat(),
        "uploaded_by": current_user["name"]
    }
    
    activity_entry = {
        "type": "video_added",
        "description": f"Video added by {current_user['name']}",
        "user": current_user["name"],
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "data": {"video_url": video_url}
    }
    
    await db.property_leads.update_one(
        {"id": lead_id},
        {
            "$push": {
                "videos": video_entry,
                "activity": activity_entry
            }
        }
    )
    
    # If landing page exists, add video there too
    if lead.get("landing_page_id"):
        await db.landing_pages.update_one(
            {"id": lead["landing_page_id"]},
            {
                "$push": {"videos": {
                    "id": video_entry["id"],
                    "source": "upload",
                    "url": video_url,
                    "title": video_entry["title"],
                    "thumbnail": "",
                    "order": 0
                }},
                "$set": {"updated_at": datetime.now(timezone.utc).isoformat()}
            }
        )
    
    return {"message": "Video added", "video": video_entry}


# ============ PUBLISH LANDING PAGE ============

@router.post("/{lead_id}/publish-landing-page")
async def publish_lead_landing_page(
    lead_id: str,
    current_user: dict = Depends(get_current_user)
):
    """Publish the landing page associated with this lead"""
    if current_user["role"] not in [UserRole.SUPERUSER, UserRole.ADMIN]:
        raise HTTPException(status_code=403, detail="Admin access required")
    
    lead = await db.property_leads.find_one({"id": lead_id}, {"_id": 0})
    if not lead:
        raise HTTPException(status_code=404, detail="Property lead not found")
    
    if not lead.get("landing_page_id"):
        raise HTTPException(status_code=400, detail="No landing page exists for this lead. Create one first.")
    
    landing_page = await db.landing_pages.find_one({"id": lead["landing_page_id"]}, {"_id": 0})
    if not landing_page:
        raise HTTPException(status_code=404, detail="Landing page not found")
    
    now = datetime.now(timezone.utc).isoformat()
    
    await db.landing_pages.update_one(
        {"id": lead["landing_page_id"]},
        {"$set": {"status": "published", "updated_at": now}}
    )
    
    await db.property_leads.update_one(
        {"id": lead_id},
        {"$push": {"activity": {
            "type": "landing_page_published",
            "description": f"Landing page published by {current_user['name']}",
            "user": current_user["name"],
            "timestamp": now,
            "data": {"url": build_landing_page_url(landing_page["slug"])}
        }}}
    )
    
    return {
        "message": "Landing page published",
        "url": build_landing_page_url(landing_page["slug"])
    }


# ============ FULL MARKETING WORKFLOW ============

@router.post("/{lead_id}/marketing-workflow")
async def run_marketing_workflow(
    lead_id: str,
    background_tasks: BackgroundTasks,
    template: str = "flyer",
    current_user: dict = Depends(get_current_user)
):
    """
    Run the full marketing workflow:
    1. Ensure listing exists (create if needed)
    2. Ensure landing page exists and is published
    3. Generate brochure with QR code
    4. Send email to owner with brochure and landing page link
    """
    if current_user["role"] not in [UserRole.SUPERUSER, UserRole.ADMIN]:
        raise HTTPException(status_code=403, detail="Admin access required")
    
    lead = await db.property_leads.find_one({"id": lead_id}, {"_id": 0})
    if not lead:
        raise HTTPException(status_code=404, detail="Property lead not found")
    
    # Validate owner email
    recipient_email = lead.get("owner_email")
    if not recipient_email:
        raise HTTPException(
            status_code=400, 
            detail="Owner email is required for marketing workflow. Please add owner email first."
        )
    
    results = {
        "lead_id": lead_id,
        "steps": []
    }
    
    # Step 1: Ensure listing exists
    if not lead.get("listing_id"):
        listing_result = await create_listing_from_lead(
            lead_id=lead_id,
            request=CreateListingFromLeadRequest(create_landing_page=True, theme="luxury"),
            current_user=current_user
        )
        results["steps"].append({
            "step": "create_listing",
            "success": True,
            "listing_id": listing_result["listing_id"],
            "landing_page_id": listing_result.get("landing_page_id")
        })
        
        # Refresh lead data
        lead = await db.property_leads.find_one({"id": lead_id}, {"_id": 0})
    else:
        results["steps"].append({
            "step": "create_listing",
            "success": True,
            "message": "Listing already exists",
            "listing_id": lead["listing_id"]
        })
    
    # Step 2: Ensure landing page is published
    if lead.get("landing_page_id"):
        landing_page = await db.landing_pages.find_one({"id": lead["landing_page_id"]}, {"_id": 0})
        if landing_page and landing_page.get("status") != "published":
            await publish_lead_landing_page(lead_id, current_user)
            results["steps"].append({
                "step": "publish_landing_page",
                "success": True,
                "url": build_landing_page_url(landing_page["slug"])
            })
        elif landing_page:
            results["steps"].append({
                "step": "publish_landing_page",
                "success": True,
                "message": "Landing page already published",
                "url": build_landing_page_url(landing_page["slug"])
            })
    
    # Step 3: Email brochure
    email_request = EmailBrochureRequest(
        template=template,
        recipient_email=recipient_email,
        include_landing_page_link=True
    )
    
    email_result = await email_brochure(
        lead_id=lead_id,
        request=email_request,
        background_tasks=background_tasks,
        current_user=current_user
    )
    
    results["steps"].append({
        "step": "email_brochure",
        "success": True,
        "recipient": recipient_email,
        "template": template,
        "landing_page_url": email_result.get("landing_page_url")
    })
    
    results["message"] = "Marketing workflow initiated successfully"
    results["recipient"] = recipient_email
    
    return results


# ============ PROPERTY DATA SCRAPER ============

@router.post("/{lead_id}/generate-data")
async def generate_property_data(
    lead_id: str,
    current_user: dict = Depends(get_current_user)
):
    """
    Scrape property data from Zillow, Redfin, and Realtor.com
    Updates the lead with found data and images
    """
    if current_user["role"] not in [UserRole.SUPERUSER, UserRole.ADMIN]:
        raise HTTPException(status_code=403, detail="Admin access required")
    
    lead = await db.property_leads.find_one({"id": lead_id}, {"_id": 0})
    if not lead:
        raise HTTPException(status_code=404, detail="Property lead not found")
    
    address = lead.get("address")
    city = lead.get("city")
    state = lead.get("state", "FL")
    zip_code = lead.get("zip_code", "")
    
    if not address or not city:
        raise HTTPException(status_code=400, detail="Address and city are required for property lookup")
    
    # Scrape property data
    scrape_result = await scrape_property_data(address, city, state, zip_code)
    
    # Prepare update data
    update_data = {
        "scraped_data": scrape_result,
        "last_scraped_at": datetime.now(timezone.utc).isoformat(),
        "updated_at": datetime.now(timezone.utc).isoformat()
    }
    
    # Update lead with scraped data if found
    if scrape_result.get("success") and scrape_result.get("data"):
        scraped = scrape_result["data"]
        
        # Only update fields that are empty in the lead
        if scraped.get("price") and not lead.get("estimated_value"):
            update_data["estimated_value"] = scraped["price"]
        if scraped.get("bedrooms") and not lead.get("bedrooms"):
            update_data["bedrooms"] = int(scraped["bedrooms"])
        if scraped.get("bathrooms") and not lead.get("bathrooms"):
            update_data["bathrooms"] = float(scraped["bathrooms"])
        if scraped.get("sqft") and not lead.get("sqft"):
            update_data["sqft"] = int(scraped["sqft"])
        if scraped.get("year_built") and not lead.get("year_built"):
            update_data["year_built"] = int(scraped["year_built"])
        if scraped.get("lot_size") and not lead.get("lot_size"):
            update_data["lot_size"] = scraped["lot_size"]
        if scraped.get("property_type") and not lead.get("property_type"):
            update_data["property_type"] = scraped["property_type"]
        if scraped.get("description") and not lead.get("description"):
            update_data["description"] = scraped["description"]
        if scraped.get("zestimate"):
            update_data["zestimate"] = scraped["zestimate"]
    
    # Store images
    if scrape_result.get("images"):
        update_data["scraped_images"] = scrape_result["images"]
    
    # Store street view
    if scrape_result.get("street_view"):
        update_data["street_view"] = scrape_result["street_view"]
    
    # Log activity
    activity_entry = {
        "type": "data_generated",
        "description": f"Property data scraped from {', '.join(scrape_result.get('sources_found', []))} by {current_user['name']}",
        "user": current_user["name"],
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "data": {
            "sources_found": scrape_result.get("sources_found", []),
            "images_found": len(scrape_result.get("images", [])),
            "data_fields": list(scrape_result.get("data", {}).keys())
        }
    }
    
    await db.property_leads.update_one(
        {"id": lead_id},
        {
            "$set": update_data,
            "$push": {"activity": activity_entry}
        }
    )
    
    # Get updated lead
    updated_lead = await db.property_leads.find_one({"id": lead_id}, {"_id": 0})
    
    return {
        "success": scrape_result.get("success", False),
        "message": f"Found data from {len(scrape_result.get('sources_found', []))} sources" if scrape_result.get("success") else "No data found from any source",
        "sources_found": scrape_result.get("sources_found", []),
        "source_urls": scrape_result.get("source_urls", {}),
        "data_found": scrape_result.get("data", {}),
        "images_count": len(scrape_result.get("images", [])),
        "images": scrape_result.get("images", [])[:10],  # Return first 10 images in response
        "street_view": scrape_result.get("street_view"),
        "errors": scrape_result.get("errors", {}),
        "lead": updated_lead
    }


@router.post("/{lead_id}/convert-to-showcase")
async def convert_lead_to_showcase(
    lead_id: str,
    current_user: dict = Depends(get_current_user)
):
    """
    Convert a property lead to a showcase listing
    Creates a full listing with all scraped data and images
    """
    if current_user["role"] not in [UserRole.SUPERUSER, UserRole.ADMIN]:
        raise HTTPException(status_code=403, detail="Admin access required")
    
    lead = await db.property_leads.find_one({"id": lead_id}, {"_id": 0})
    if not lead:
        raise HTTPException(status_code=404, detail="Property lead not found")
    
    # Check if listing already exists
    if lead.get("listing_id"):
        existing = await db.properties.find_one({"id": lead["listing_id"]}, {"_id": 0})
        if existing:
            # Update existing listing with scraped data
            update_fields = {}
            if lead.get("scraped_images") and not existing.get("images"):
                update_fields["images"] = [img["url"] for img in lead["scraped_images"][:20]]
            if lead.get("street_view"):
                update_fields["street_view"] = lead["street_view"]
            
            if update_fields:
                update_fields["updated_at"] = datetime.now(timezone.utc).isoformat()
                await db.properties.update_one({"id": lead["listing_id"]}, {"$set": update_fields})
            
            return {
                "message": "Listing updated with scraped data",
                "listing_id": lead["listing_id"],
                "listing": await db.properties.find_one({"id": lead["listing_id"]}, {"_id": 0})
            }
    
    now = datetime.now(timezone.utc).isoformat()
    listing_id = str(uuid.uuid4())
    
    # Get images from scraped data
    images = []
    if lead.get("scraped_images"):
        images = [img["url"] for img in lead["scraped_images"][:20]]
    
    # Create showcase listing
    listing = {
        "id": listing_id,
        "title": lead.get("address", "Property"),
        "address": lead.get("address", ""),
        "city": lead.get("city", ""),
        "state": lead.get("state", "FL"),
        "zip_code": lead.get("zip_code", ""),
        "county": lead.get("county", ""),
        "price": lead.get("estimated_value") or lead.get("scraped_data", {}).get("data", {}).get("price"),
        "property_type": lead.get("property_type", "single_family"),
        "bedrooms": lead.get("bedrooms"),
        "bathrooms": lead.get("bathrooms"),
        "sqft": lead.get("sqft"),
        "square_feet": lead.get("sqft"),
        "lot_size": lead.get("lot_size"),
        "year_built": lead.get("year_built"),
        "description": lead.get("description") or lead.get("scraped_data", {}).get("data", {}).get("description", ""),
        "features": [],
        "images": images,
        "street_view": lead.get("street_view"),
        "status": "showcase",
        "is_showcase": True,
        "mls_number": "",
        "source": "property_lead",
        "source_lead_id": lead_id,
        "source_urls": lead.get("scraped_data", {}).get("source_urls", {}),
        "zestimate": lead.get("zestimate") or lead.get("scraped_data", {}).get("data", {}).get("zestimate"),
        "created_at": now,
        "updated_at": now
    }
    
    await db.properties.insert_one(listing)
    
    # Update lead with listing reference
    await db.property_leads.update_one(
        {"id": lead_id},
        {
            "$set": {
                "listing_id": listing_id,
                "status": "converted",
                "updated_at": now
            },
            "$push": {"activity": {
                "type": "converted_to_showcase",
                "description": f"Converted to showcase listing by {current_user['name']}",
                "user": current_user["name"],
                "timestamp": now,
                "data": {
                    "listing_id": listing_id,
                    "images_count": len(images)
                }
            }}
        }
    )
    
    return {
        "message": "Property lead converted to showcase listing",
        "listing_id": listing_id,
        "listing": listing,
        "images_added": len(images)
    }


# ============ LISTINGS DATA SCRAPER ============

@router.post("/listings/{listing_id}/generate-data")
async def generate_listing_data(
    listing_id: str,
    current_user: dict = Depends(get_current_user)
):
    """
    Scrape property data for an existing listing
    Updates the listing with found data and images
    """
    if current_user["role"] not in [UserRole.SUPERUSER, UserRole.ADMIN]:
        raise HTTPException(status_code=403, detail="Admin access required")
    
    listing = await db.properties.find_one({"id": listing_id}, {"_id": 0})
    if not listing:
        raise HTTPException(status_code=404, detail="Listing not found")
    
    address = listing.get("address")
    city = listing.get("city")
    state = listing.get("state", "FL")
    zip_code = listing.get("zip_code", "")
    
    if not address or not city:
        raise HTTPException(status_code=400, detail="Address and city are required for property lookup")
    
    # Scrape property data
    scrape_result = await scrape_property_data(address, city, state, zip_code)
    
    # Prepare update data
    update_data = {
        "scraped_data": scrape_result,
        "last_scraped_at": datetime.now(timezone.utc).isoformat(),
        "updated_at": datetime.now(timezone.utc).isoformat()
    }
    
    # Update listing with scraped data if found
    if scrape_result.get("success") and scrape_result.get("data"):
        scraped = scrape_result["data"]
        
        # Only update fields that are empty
        if scraped.get("price") and not listing.get("price"):
            update_data["price"] = scraped["price"]
        if scraped.get("bedrooms") and not listing.get("bedrooms"):
            update_data["bedrooms"] = int(scraped["bedrooms"])
        if scraped.get("bathrooms") and not listing.get("bathrooms"):
            update_data["bathrooms"] = float(scraped["bathrooms"])
        if scraped.get("sqft") and not listing.get("sqft"):
            update_data["sqft"] = int(scraped["sqft"])
            update_data["square_feet"] = int(scraped["sqft"])
        if scraped.get("year_built") and not listing.get("year_built"):
            update_data["year_built"] = int(scraped["year_built"])
        if scraped.get("lot_size") and not listing.get("lot_size"):
            update_data["lot_size"] = scraped["lot_size"]
        if scraped.get("description") and not listing.get("description"):
            update_data["description"] = scraped["description"]
        if scraped.get("zestimate"):
            update_data["zestimate"] = scraped["zestimate"]
    
    # Store/update images
    if scrape_result.get("images") and not listing.get("images"):
        update_data["images"] = [img["url"] for img in scrape_result["images"][:20]]
    
    # Store street view
    if scrape_result.get("street_view"):
        update_data["street_view"] = scrape_result["street_view"]
    
    # Store source URLs
    if scrape_result.get("source_urls"):
        update_data["source_urls"] = scrape_result["source_urls"]
    
    await db.properties.update_one({"id": listing_id}, {"$set": update_data})
    
    # Get updated listing
    updated_listing = await db.properties.find_one({"id": listing_id}, {"_id": 0})
    
    return {
        "success": scrape_result.get("success", False),
        "message": f"Found data from {len(scrape_result.get('sources_found', []))} sources" if scrape_result.get("success") else "No data found",
        "sources_found": scrape_result.get("sources_found", []),
        "source_urls": scrape_result.get("source_urls", {}),
        "data_found": scrape_result.get("data", {}),
        "images_count": len(scrape_result.get("images", [])),
        "street_view": scrape_result.get("street_view"),
        "listing": updated_listing
    }

